### ISSUE TITLE
config_settings does not override the default value

### ISSUE THREAD

**Issue by daivinhtran** [bazelbuild/rules_testing#95]
I have a [test](https://github.com/bazelbuild/rules_rust/pull/2414/files#diff-fa937bd62455d6a9abe6f107fc39d163b41556ffa425a13746541775c5641df1) that tests a feature behind a [config setting](https://github.com/bazelbuild/rules_rust/pull/2414/files#diff-50f3b23cb7e50cd5c4e6ebaebca168002673b4cb864b5a377b0ceec3ee7f4c05).

Setting

```
        config_settings = {"@rules_rust//rust/settings:experimental_link_std_dylib": True},
```

on `analysis_test` does not override the setting correctly in the test environment.

Note that the config setting is set on [the toolchain rule](https://github.com/bazelbuild/rules_rust/pull/2414/files#diff-2a806da393e47c07ffe67c78ace69eb488b4ac44b029a46d8237b8e2a05637beR737), not the rule that the test is testing. I think the transition that handles setting the config_settings has some bug.

**Comment by daivinhtran** [comment]
I saw `config_settings` is tested in https://github.com/bazelbuild/rules_testing/blob/1dfcb4ff948d73d5085b41a14842dcddf1baca85/tests/analysis_test_tests.bzl#L292-L294.

However, I noticed `config_settings` only works for tests in `rules_testing` repo.

If I have a test that has

```
        config_settings = {
            "//test/link_std_dylib:flag_b": True,
        },
```

it fails with

`
On dependency edge //test/link_std_dylib:test_rust_binary (441a6c1) -|target|-> //test/link_std_dylib:test_rust_binary_rust_binary: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package '@@rules_testing//test/link_std_dylib': BUILD file not found in directory 'test/link_std_dylib' of external repository @@rules_testing.
`

These config setting targets are resolved against the `rules_testing` workspace instead of the workspace triggering the test.

**Comment by daivinhtran** [comment]
Ahh I have to use

```
        config_settings = {
            str(Label("@rules_rust//rust/settings:experimental_link_std_dylib")): True,
        },
```

instead of

        config_settings = {
            "@rules_rust//rust/settings:experimental_link_std_dylib": True,
        },

**Comment by fmeum** [comment]
@rickeylev I would recommend failing if a user passes in a non-main repo label that isn't canonical. Ideally users could and would pass in typed `Label` objects
